version: '3.7'

services:
  zipkin:
    image: openzipkin/zipkin:2.23.2
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - lab-network

networks: 
  lab-network:
    driver: bridge