logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
    # https://stackoverflow.com/a/61194878/4332063
  level:
    ROOT: INFO
server:
  port: 8080
spring:
  application:
    name: lab-trancing-api2
  sleuth:
    sampler:
      percentage: 1.0

management: # https://www.baeldung.com/spring-boot-actuators#2-important-changes
  context-path: /management
  security:
    enabled: false
  defaults:
    metrics:
      export:
        enabled: false
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: configprops, env, health, info, jhimetrics, logfile, loggers, prometheus, threaddump, metrics, shutdown # include: "*" # include todos os serviços do actuator
  metrics:
    export:
      prometheus:
        enabled: true
        step: PT60s # https://stackoverflow.com/a/62412593
    use-global-registry: false
